server:
  port: 8200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: dummy-service
  sleuth:
    sampler:
      probability: 1.0
  #zipkin:
    #base-url: http://localhost:9411/